import type { Metadata } from "next";
import "./globals.css";

import Dashboard from "./Dashboard/page";

export const metadata: Metadata = {
  title: "Xpenso",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Dashboard />
        {children}
      </body>
    </html>
  );
}
